spring:
  application:
    name: usian-item-web
  rabbitmq:
    host: 127.0.0.1
    username: admin
    password: admin
    virtual-host: /
server:
  port: 8091
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
ribbon:
  eureka:
    enabled: true
feign:
  hystrix:
    enabled: true #开启降级处理
    command:
      default:
        circuitBreaker:
          requestVolumeThreshold: 3
          errorThresholdPercentage: 5
          sleepWindowInMilliseconds: 5000

        #第一层 hystrix 超时时间设置
        execution:
          isolation:
            thread:
              timeoutInMilliseconds: 8000 #默认情况下是线程池隔离，超时时间 1000ms
  #第二层 ribbon 超时时间设置：设置比第一层小
  ribbon:
    ConnectTimeout: 3000 #请求连接的超时时间: 默认 5s
    ReadTimeout: 3000 #请求处理的超时时间: 默认 5s
